### ISSUE TITLE
Error: Cannot find module 'gift'

### ISSUE THREAD

**Issue by BastienLQ** [notatestuser/gift#54]
Hi,

Here is a simple code:
```
$ cat gift.js
var git = require("gift");
```

With the latest gift package, this code will not work:
```
$ node gift.js

module.js:340
    throw err;
          ^
Error: Cannot find module 'gift'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/bastien/nodejs/gift-test/gift.js:1:73)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
```

Node.js cannot find `gift` because libs are missing in gift@0.5.0:
```
$ ls node_modules/gift/
LICENSE  node_modules  package.json  README.md  src  test
```

I assume `prepublish` task has not been launched. So gift@0.5.0 must be republished.

Thanks.

**Comment by notatestuser** [comment]
The compiled sources are in the npm tarball: `https://registry.npmjs.org/gift/-/gift-0.5.0.tgz`
