### ISSUE TITLE
Handling of special characters

### ISSUE THREAD

**Issue by deployable** [notatestuser/gift#79]
There's doesn't appear to be any handling of special shell characters in gift when options and arguments are passed to bash. 

And path with spaces or special characters in the arguments blow up with 

```
Unhandled rejection Error: spawn /bin/sh ENOENT
    at exports._errnoException (util.js:874:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:439:9)
    at process._tickCallback (node.js:353:17)

Unhandled rejection Error: ENOENT: no such file or directory, open '/app/fixture/re po/event_rules_spec.yml.saved'
    at Error (native)
```

Trying to escape paths at the front end causes more issues so I think it needs to be handled in gift. 

The Shellwords module from ruby has the most useful [shellescape implementation](https://github.com/ruby/ruby/blob/trunk/lib/shellwords.rb#L142) I've used.

The best nodejs example I could [find is on stack](https://stackoverflow.com/a/7685469):
```
'"' + cmd.replace(/(["\s'$`\\])/g,'\\$1') + '"'
```

Do all exec calls in gift go through the [`git` function](https://github.com/notatestuser/gift/blob/f971f0702dc280b50e532dc092b9c60fc5060a3f/src/git.coffee#L8)?  Is it normally `args` that would pass path/file names?

**Comment by deployable** [comment]
Actually, using [`spawn`](https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options) in probably a much better way to deal with this. No shell shenanigans.
